---
- name: Install "requirements" packages
  become: true
  apt:
    name: libcap2-bin
    state: present
    update_cache: "yes"

- name: "Create app group"
  become: true
  group:
    name: "{{ matraefik_group }}"
    state: "present"

- name: "Create app user"
  become: true
  user:
    name: "{{ matraefik_user }}"
    groups: "{{ matraefik_alternate_groups }}"
    group: "{{ matraefik_group }}"
    append: 'yes'

- name: "Create basics directories"
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ matraefik_user }}"
    group: "{{ matraefik_group }}"
    mode: 0755
  with_items:
    - "/etc/traefik"
    - "/etc/traefik/acme"

- name: "Download Traefik binary"
  get_url:
    url: "{{ matraefik_binary_url }}"
    dest: "/usr/bin/traefik"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Add capabilities on traefik for 80 listening
  capabilities:
    path: /usr/bin/traefik
    capability: CAP_NET_BIND_SERVICE+eip
    state: present
  become: true

- name: Create configuration
  become: true
  template:
    src: "{{ matraefik_conf_template }}"
    dest: "/etc/traefik/conf.toml"
    owner: "{{ matraefik_user }}"
    group: "{{ matraefik_group }}"
    mode: 0644
  notify:
    - restart traefik systemd unit

- name: Create systemd unit
  become: true
  template:
    src: systemd.j2
    dest: "/etc/systemd/system/traefik.service"
  notify:
    - enable traefik systemd unit
    - restart traefik systemd unit

- name: Make sure traefik service is started and enabled
  systemd:
    state: "started"
    name: "traefik"
    enabled: yes
